server:
  port: 80
  
feign:
  hystrix:
    enabled: true  #开启Hystrix服务降级

eureka:
  client:
    register-with-eureka: false    #false表示不向注册中心注册自己。
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  # 提供者实例信息配置，完善actuator监控信息
  instance:
    instance-id: microservicecloud-consumer-dept80
    prefer-ip-address: true     #注册的服务实例访问路径可以显示IP地址

# 整合actuator监控信息
info:
  app.name: wzm-microservicecloud
  company.name: www.wzm.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$